# Generated by Django 4.0.7 on 2024-05-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0003_rename_name_notes_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='UserNote',
        ),
    ]
