# Generated by Django 4.0.7 on 2024-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0005_delete_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
