# Generated by Django 4.0.7 on 2024-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0006_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date_added', models.CharField(max_length=255)),
            ],
        ),
    ]
