# Generated by Django 4.0.7 on 2024-05-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0008_groupteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupteam',
            name='createdby',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
