# Generated by Django 4.0.7 on 2024-05-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0009_groupteam_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupteam',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
