# Generated by Django 4.0.7 on 2024-05-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0010_alter_groupteam_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cId', models.CharField(max_length=255)),
                ('groupname', models.CharField(max_length=255)),
                ('taskdetails', models.CharField(max_length=255)),
                ('taskstatus', models.CharField(max_length=255)),
            ],
        ),
    ]
